---
- hosts: all
  tasks:
    - name: Prints various Asnible facts
      ansible.builtin.debug:
        msg: >
          The default Ipv4 address of {{ ansible_facts.fqdn }}
          is {{ ansible_facts.default_ipv4.address }}
